name: "vprofile IAC"
on: 
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

jobs:
  terraform:
    name: "Apply terraform packages"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
      AWS_REGION: "us-east-2"
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      -  name:  "checkout repository"
         uses: actions/checkout@v3   

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
           
   
      - name: "Terraform Init"
        id: init
        run: |
          terraform init \
          -backend-config="bucket=${BUCKET_TF_STATE}" \
      
      - name: "Terraform format check"
        id: fmt
        run: |
          terraform fmt -check

      - name: "Terraform Validate"
        id: "Validate"
        run: |
          terraform validate

      - name: "Terraform Plan"
        id: "Plan"
        run: |
          terraform plan -no-color -input=false -out=tfplan
        continue-on-error: true

      - name: Terraform plan status
        if: steps.Plan.outcome == 'failure'
        run: exit 1
        

        
